language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=1.8.17

before_install:
  - export DJANGO_SETTINGS_MODULE=cdtool.settings
  - export PYTHONPATH=$HOME/builds/samirelanduk/cdtool
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - python manage.py test cdcrunch
  - python manage.py test home
